### ISSUE TITLE
`--sloc` includes unittests

### ISSUE THREAD

**Issue by jkm** [Hackerpilot/Dscanner#220]
I'd like to count the number of source lines excluding code in unittest blocks. Any easy way to achive this?
Thanks.

**Comment by Hackerpilot** [comment]
The implementation is located here: https://github.com/Hackerpilot/Dscanner/blob/master/src/stats.d

As you can see the code has no idea if it's in a unittest block or not, so adding this will not be trivial.

**Comment by jkm** [comment]
I see. Just wanted to make sure. Maybe I try to remove the unittest blocks with some shell fu.
Thanks for dscanner. Very useful to me.
