### ISSUE TITLE
support emacs etags format

### ISSUE THREAD

**Issue by MartinNowak** [Hackerpilot/Dscanner#223]
There should be a `-e` flag to output emacs compatile tags.
https://github.com/drothlis/clang-ctags

**Comment by Hackerpilot** [comment]
Why is the specification for etags files so hard to find...

**Comment by MartinNowak** [comment]
That's the best I found.
http://en.wikipedia.org/wiki/Ctags#Etags_2
[Understanding the `ctags -e` file format (ctags for emacs)](http://stackoverflow.com/questions/1990579/understanding-the-ctags-e-file-format-ctags-for-emacs)

**Comment by smolt** [comment]
I worked on etags option last night and works pretty good, scanning all of phobos/druntime.  dparse and ctags.d as a starting point made this enjoyable.  Works well with a vanilla GNU Emacs builtin tags support.

Except I need to tune what is tagged.  I'm tagging too much stuff (stuff in unittests, all function scoped declarations).  Also, experimenting with emitting all tags with full module scope (e.g. "std.stdio.File").  That seems like the right thing to do, `M-. File` does the right thing, but `M-x complete-tag` needs module name ("Fi" won't complete to "File", would need "std.stdio.Fi".).   I'll cleanup what I have and make a pull request this week.

**Comment by MartinNowak** [comment]
Nice!

**Comment by smolt** [comment]
PR #237.  Still needs more testing but seems to find declarations I expect in phobos and druntime.

**Comment by smolt** [comment]
@Hackerpilot - Does something under Attribute node have protection (public,private,package,protected)?  I am imagining a cmdline option to limit etags to public/protected declarations.  It maybe should be the default.  I've got a couple other updates too, like tagging aliases & modules, and a fix for anon structs (they are incorrectly tagged).

**Comment by Hackerpilot** [comment]
There's a static analysis check for undocumented public symbols. You might be able to re-use some of that code.
