### ISSUE TITLE
file(line:col)=>file(line,col) (use same convention as in DMD)

### ISSUE THREAD

**Issue by timotheecour** [Hackerpilot/Dscanner#224]
Why use a different convention? it breaks existing tooling that assumes dmd's convention (file(line,col)) when reporting messages (eg with dscanner --declaration)

**Comment by Hackerpilot** [comment]
clang and gcc both use ":", so the question is "Why does dmd break existing tooling"?

**Comment by timotheecour** [comment]
makes sense.
sent an email on forum
EMAIL:file(line,col)=>file(line:col) to follow convention of clang,gcc,dscanner etc
