### ISSUE TITLE
libdparse/src/std/d/lexer.d(633): Error: template instance skip!(true, '\x09', ' ', '\x0b', '\x0c') template 'skip' is not defined

### ISSUE THREAD

**Issue by timotheecour** [Hackerpilot/Dscanner#227]
git clone https://github.com/Hackerpilot/Dscanner.git
cd Dscanner
git submodule update --init --recursive
make

libdparse/src/std/d/lexer.d(633): Error: template instance skip!(true, '\x09', ' ', '\x0b', '\x0c') template 'skip' is not defined

it used to work about a week ago

**Comment by Hackerpilot** [comment]
I just looked at yesterday's commits, they do point at the correct libdparse versions. I'm not sure what's going on with your checkout.

**Comment by timotheecour** [comment]
could you try the above command?
it's failing on 2 different machines.
git submodule update --init --recursive
now actually fails with:
fatal: reference is not a tree: 89dbc9a27e1187285977cdd708cdbf90cf8d2782

**Comment by Hackerpilot** [comment]
It should work now. There was a commit I forgot to push to libdparse.

**Comment by timotheecour** [comment]
ok thanks, now back to the original problem :
libdparse/src/std/d/lexer.d(633): Error: template instance skip!(true, '\x09', ' ', '\x0b', '\x0c') template 'skip' is not defined

After looking at that file, I see that skip(...) is defined under version (D_InlineAsm_X86_64) version (linux) 
.
which makes the code not compile on OSX (I used to compiled last time i tried). That seems like a regression.

**Comment by Hackerpilot** [comment]
I thought I had replaced all of those with ```version (iasm64NotWindows)```, but it looks like I missed one.

**Comment by Hackerpilot** [comment]
It should be fixed now.

**Comment by timotheecour** [comment]
thanks!
