### ISSUE TITLE
--declaration reports wrong line number when there are /+..+/ comments

### ISSUE THREAD

**Issue by timotheecour** [Hackerpilot/Dscanner#230]
--------
/+

+/
void main(){}
--------
dscanner --declaration main
./test.d(2:6)

after some testing it seems it just skips lines containing '/+' or '+/'

**Comment by Hackerpilot** [comment]
It looks like Github doesn't like your code formatting.

**Comment by timotheecour** [comment]
/+

+/

void main(){}

**Comment by timotheecour** [comment]
Can you reproduce the problem on your side with a file containing those 5 lines?

**Comment by Hackerpilot** [comment]
No. I'm not able to reproduce this. Which OS/CPU is this on? (Also, have you done ```git submodule update``` recently?)

**Comment by timotheecour** [comment]
ok problem was fixed after that, thanks. Closing.
