### ISSUE TITLE
warnings generated with git head dmd: "Deprecation: asm statement is assumed to ..."

### ISSUE THREAD

**Issue by timotheecour** [Hackerpilot/Dscanner#231]
Deprecation: asm statement is assumed to throw - mark it with 'nothrow' if it does not
Deprecation: asm statement is assumed to be impure - mark it with 'pure' if it is not
Deprecation: asm statement is assumed to use the GC - mark it with '@nogc' if it does not

**Comment by Hackerpilot** [comment]
If I add these nobody will be able to compile with 2.066.x.

**Comment by Hackerpilot** [comment]
Also tracked here: https://github.com/Hackerpilot/libdparse/issues/50

**Comment by timotheecour** [comment]
Hackerpilot/libdparse#50 seems a bit different.
2.067.1 has been out for sometime now, could we revisit this?
if you're worried about compatibility with 2.066 there's always version(...) depending on which compiler version.
