### ISSUE TITLE
wish: non-zero exit code if any checks are failed

### ISSUE THREAD

**Issue by denizzzka** [Hackerpilot/Dscanner#239]
(useful for continuous integration purposes)

**Comment by Hackerpilot** [comment]
I don't like this idea because of the number of false positives that the checks can give. This may be a good idea some time in the future, but it isn't right now.

**Comment by denizzzka** [comment]
> I don't like this idea because of the number of false positives that the checks can give

If anyone don't trusts dscanner he/she just not uses its exit code...

**Comment by Hackerpilot** [comment]
I don't trust it and I wrote it.

**Comment by denizzzka** [comment]
> I don't trust it and I wrote it.

...and you just should do not use Dscanner exit code...

If code written by small pieces (commits) and CI used it is very simple to understand where is problem if error code is catched.

**Comment by Hackerpilot** [comment]
Closing when 0.2.0 is tagged.
