### ISSUE TITLE
Warn about using a string (or array) literal as an assert condition

### ISSUE THREAD

**Issue by yebblies** [Hackerpilot/Dscanner#241]
This would catch buggy code like:
```d
assert("Message");
```
See: https://issues.dlang.org/show_bug.cgi?id=11080

**Comment by MartinNowak** [comment]
We should probably extend this to a full implicit array to bool conversion warning.
https://issues.dlang.org/show_bug.cgi?id=4733

**Comment by yebblies** [comment]
That would require semantic analysis, this does not.

**Comment by Hackerpilot** [comment]
I think I'm going to try to solve this more correctly, but doing so means using some of the symbol lookup stuff that I'm saving for the 0.3.0 release. I'm taking this out of 0.2.0.
