### ISSUE TITLE
cannot build Dscanner with dmd git head

### ISSUE THREAD

**Issue by timotheecour** [Hackerpilot/Dscanner#250]
on a fresh clone of Dscanner and using v2.068-devel-acbe13e:

git log -1 --format="%H" > githash.txt
mkdir -p bin
dmd -w -O -release -inline -ofbin/dscanner  -Ilibdparse/src src/*.d src/analysis/*.d libdparse/src/std/*.d libdparse/src/std/d/*.d inifiled/source/*.d -J.
libdparse/src/std/d/formatter.d(219): Error: std.typetuple.Arguments(TList...) at phobos/std/typetuple.d(36) conflicts with std.d.ast.Arguments at libdparse/src/std/d/ast.d(500)
libdparse/src/std/d/formatter.d(219): Error: template std.typetuple.Arguments(TList...) is used as a type
src/astprinter.d(841): Error: template instance std.d.formatter.Formatter!(Appender!string) error instantiating
libdparse/src/std/d/formatter.d(219): Error: std.typetuple.Arguments(TList...) at phobos/std/typetuple.d(36) conflicts with std.d.ast.Arguments at libdparse/src/std/d/ast.d(500)
libdparse/src/std/d/formatter.d(219): Error: template std.typetuple.Arguments(TList...) is used as a type
src/outliner.d(47): Error: template instance std.d.formatter.Formatter!(Appender!(char[])) error instantiating
src/analysis/if_statements.d(82): Error: template instance std.d.formatter.format!(Appender!string, const(ExpressionNode)) error instantiating

(+warnings for which i've already submitted a bug report)

**Comment by timotheecour** [comment]
fixed easily as follows:

in std.d.formatter:
//import std.typetuple;
import std.typetuple:TypeTuple;

**Comment by Hackerpilot** [comment]
Will you make a pull request for that?

Also, isn't the compiler supposed to issue an error or warning when it encounters a name conflict like this?

**Comment by Hackerpilot** [comment]
Disregard that. I saw your pull request.

**Comment by timotheecour** [comment]
>> Also, isn't the compiler supposed to issue an error or warning when it encounters a name conflict like this?

it does issue an error, so i'm not sure what you mean?

**Comment by Hackerpilot** [comment]
Sorry, I didn't read the error message very carefully.
