### ISSUE TITLE
request: add line: tag to ctags output

### ISSUE THREAD

**Issue by rsw0x** [Hackerpilot/Dscanner#258]
A popular vim addon [tagbar](https://github.com/majutsushi/tagbar/tree/399b75256ac7333d7119d11047f6b3aff8fa2828) that uses ctags [doesn't support reading line numbers from the standard position of ctags](https://github.com/majutsushi/tagbar/blob/master/doc/tagbar.txt#L1199-L1214), only when it's put in the line: field.

It would be nice if dscanner output is compatible with tagbar, as the output is much better than the patched for D ctags.

**Comment by Hackerpilot** [comment]
The format of the ctags output should be pretty easy for you to modify. In the mean time, you can get an outline of a source file by using the `--outline` option.
