### ISSUE TITLE
code compiles but shouldn't

### ISSUE THREAD

**Issue by timotheecour** [Hackerpilot/Dscanner#265]
after dustmite reduction of a bug i had (see https://github.com/ldc-developers/ldc/issues/954) it looks like there's a bug in Dscanner/libdparse/src/std/lexer.d:
string[] sortedTokens = array(sort!"a.length > b.length"(tokens));
(array is missing an import)

see that thread for context

**Comment by Hackerpilot** [comment]
Argh! Yet another bug caused by the front-end's broken handling of imports.

**Comment by Hackerpilot** [comment]
Please files bugs for files in the "libdparse" directory here: https://github.com/Hackerpilot/libdparse/issues
