### ISSUE TITLE
Relax comma expression warning

### ISSUE THREAD

**Issue by Hackerpilot** [Hackerpilot/Dscanner#269]
The comma expression warning should be disabled unless the comma expression appears on the RHS of an assign expression.

**Comment by CyberShadow** [comment]
The `synchronized(a, b)` error from Ali's slides doesn't seem to be detected now...

**Comment by Hackerpilot** [comment]
Fixed in https://github.com/Hackerpilot/Dscanner/commit/02f8f3c423a413d0f90e9d4698a2db9049e35b44
