### ISSUE TITLE
AUR package doesn't build

### ISSUE THREAD

**Issue by TurkeyMan** [Hackerpilot/Dscanner#296]
As mentioned in this issue: https://github.com/WebFreak001/workspace-d/issues/3#issuecomment-166862050

`yaourt -S --aur dscanner` fails
```
...
libdparse/src/std/d/lexer.d(2240): Deprecation: asm statement is assumed to be impure - mark it with 'pure' if it is not
libdparse/src/std/d/lexer.d(2240): Deprecation: asm statement is assumed to use the GC - mark it with '@nogc' if it does not
libdparse/src/std/d/lexer.d(2240): Deprecation: asm statement is assumed to throw - mark it with 'nothrow' if it does not
makefile:28: recipe for target 'dmdbuild' failed
make: *** [dmdbuild] Error 1
```

Dependency on wrong DMD version?

**Comment by Hackerpilot** [comment]
What's an AUR package?

**Comment by Vild** [comment]
AUR = ArchLinux User Repository
I am currently the maintainer for this packge.
I can confirm that dscanner 0.2.0 does not compile anymore with version 2.069 of the compiler.

What you, @TurkeyMan can do is install the dscanner-git version, which installs the latest code here from github.
I would also recommend that you use the -git versions for dcd, dfmt aswell.
You can see the packages here, https://aur.archlinux.org/packages/?K=WildN00b&SeB=m

**Comment by WebFreak001** [comment]
This was fixed as of January, I think this can be closed. Can @TurkeyMan confirm that it works now?

**Comment by wilzbach** [comment]
> This was fixed as of January, I think this can be closed. Can @TurkeyMan confirm that it works now?

I use Arch now and can confirm that both `dscanner` and `dscanner-git` are building.
Thankd @Vild!
