### ISSUE TITLE
githash.txt

### ISSUE THREAD

**Issue by tsbockman** [Hackerpilot/Dscanner#297]
The latest DUB version fails to build:
```
Performing "debug" build using dmd for x86_64.
inifiled 0.0.6: target for configuration "library" is up to date.
libdparse 0.2.1: target for configuration "library" is up to date.
dscanner 0.2.0: building configuration "application"...
Running pre-build commands...
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Command failed with exit code 128
```
Also, this pre-build command: `git log -1 --format='%H' > githash.txt` puts a file in the current working directory, rather than the project directory. So, running `dub build dscanner` will dump `githash.txt` in whatever random folder the command is run from.

**Comment by Hackerpilot** [comment]
Fixed in https://github.com/Hackerpilot/Dscanner/commit/ecf476a341e33af52ff65cfa06bc2164502c3d05 and https://github.com/Hackerpilot/Dscanner/commit/ab08f0b28b2851063e273f5f8073b575a4d17083
