### ISSUE TITLE
Documented option --recursive not implemented

### ISSUE THREAD

**Issue by Wyatts** [Hackerpilot/Dscanner#301]
I was going to use it to make a tags file, but it throws 16k of template spew on stderr simply for being unrecognised.

**Comment by Hackerpilot** [comment]
It was removed in https://github.com/Hackerpilot/Dscanner/commit/75a6436f58345aad98effee687dab60e5b1aeca0, though I have no idea why...

**Comment by Hackerpilot** [comment]
I figured it out. The `--recursive` option was removed because that is now the default behavior for directory arguments. I'm going to fix the README.
