### ISSUE TITLE
Dscanner UDA template errors expecting declaration

### ISSUE THREAD

**Issue by eco** [Hackerpilot/Dscanner#313]
Using vibe.d's `before` UDA I was getting errors from dfmt and dscanner. Reduced:
```d
void i() { }
auto before(alias Hook)(string parameter_name) { }

@before!i("_")
void main() { }
```

Dscanner says this is an error: `attrexpectdecl.d(4:10)[error]: Declaration expected`.

`@before!(i)("_")` produces the same error. `@before!(i("_"))` silences the error but is not correct (dmd correctly errors out on this).

**Comment by Hackerpilot** [comment]
That's valid?

**Comment by eco** [comment]
`¯\_(ツ)_/¯`

For reference, here's [Vibe.d's doc page for `before`](http://vibed.org/api-0.7.19/vibe.internal.meta.funcattr/before).
