### ISSUE TITLE
status of std.lexer for Phobos

### ISSUE THREAD

**Issue by greenify** [Hackerpilot/Dscanner#316]
Hey I saw that you were trying to push your lexer to Phobos and as this is one of the most popular (if not the top most) you should have a enough supporters. What were the reasons why it got stalled?

**Comment by Hackerpilot** [comment]
The lexer is in https://github.com/Hackerpilot/libdparse/

The big reasons are that everybody had their own design goals and that getting things through the review process is a pain.
