### ISSUE TITLE
Linting for Phobos

### ISSUE THREAD

**Issue by wilzbach** [Hackerpilot/Dscanner#322]
It would be amazing to see Dscanner used at Phobos for automatic linting and enforcement of the style guide.
As you mentioned in #316 it's still a long way for `std.lexer`, but maybe we can convenience the Phobos group if we slowly start the integration by using Dscanner for linting. I guess if it's an optional target like `lint` complaints will be low. There are probably many, many errors which have to be fixed then, but eventually we could go for the autotester then :)

How difficult do you imagine it to be integrated (via git clones) into the Phobos makefiles?

**Comment by wilzbach** [comment]
It wasn't that terribly difficult to convince people to run [Dscanner on Travis](https://github.com/dlang/phobos/pull/4243), so maybe we can tackle integration to the Makefile next.
Do you prefer `git clone` or `dub`?

**Comment by MartinNowak** [comment]
Seems there are still some issues w/ the dub packaging, I get some linking errors (about duplicate std.experimental.allocator) when using `dub fetch dscanner --version=0.4.0-alpha4` and `dub build dscanner` with dmd-2.071.0.

**Comment by wilzbach** [comment]
Closing as Dscanner is successfully used at Phobos to enforce some basic style guidelines.
Thanks a lot for your great support @Hackerpilot!
