### ISSUE TITLE
Add ability to ignore/slience individual linter warnings

### ISSUE THREAD

**Issue by JackStouffer** [Hackerpilot/Dscanner#330]
This would be useful for something like using dscanner for Phobos because many of Phobos' unit tests create unused variables for testing.

**Comment by wilzbach** [comment]
@JackStouffer Do you know about the custom `dscanner.ini`?

**Comment by JackStouffer** [comment]
I don't; would be great if there were some docs for it.

**Comment by wilzbach** [comment]
It is part of the `--help`, but not of the Readme

```
    --config <file>
        Use the given configuration file instead of the default located in
        $HOME/.config/dscanner/dscanner.ini

    --defaultConfig
        Generates a default configuration file for the static analysis checks
```

Btw for a "real world example", see [mir](https://github.com/wilzbach/mir/blob/dscanner/.dscanner.ini) (pending PR)
