### ISSUE TITLE
Check for config file upwards in the file tree

### ISSUE THREAD

**Issue by wilzbach** [Hackerpilot/Dscanner#332]
The idea is that if no config file is passed as argument, it should traverse the directory tree upwards until 1) the root, 2) it found a config file, 3) it found a `.git` folder . 3) saves a bit of time as usually one wants to have a dscanner file only for one git project.

I imagine this to be quite useful for the users of dscanner as one doesn't need to specify the ini file anymore and it can automatically detect it then.

**Comment by v--** [comment]
I've implemented some base functionality for per-project files (see #349), I guess this issue is resolved?.

**Comment by wilzbach** [comment]
> I've implemented some base functionality for per-project files

Yes. Thanks a lot!
