### ISSUE TITLE
Cannot handle auto and const assignments in if-statement expression

### ISSUE THREAD

**Issue by nordlow** [Hackerpilot/Dscanner#343]
Dscanner incorrectly errors for constructs

``` D
if (auto x = f()) {}
```

and

``` D
if (const x = f()) {}
```

**Comment by wilzbach** [comment]
What error or warning does it yield?

**Comment by nordlow** [comment]
```D
unittest
{
    static int f()
    {
        return 42;
    }
    if (const x = f())
    {
    }
}
```D
errors as


```D
Expected ( instead of =
Primary expression expected
```

**Comment by wilzbach** [comment]
That's probably a libdparse bug and maybe even related to [this](https://github.com/Hackerpilot/libdparse/issues/99) ...

**Comment by BBasile** [comment]
This is fixed in libdparse [by this PR](https://github.com/Hackerpilot/libdparse/pull/122). However the submodule and the JSON may have to be updated before closing.

**Comment by Hackerpilot** [comment]
As of 0.4.0-beta.4 this file parses without errors:

```d
void main()
{
	if (auto x = f())
	{
	}
	if (const x = f())
	{
	}
}
```

**Comment by nordlow** [comment]
Great!
