### ISSUE TITLE
Add ability to resolve import module file locations

### ISSUE THREAD

**Issue by jcrapuchettes** [Hackerpilot/Dscanner#355]
It would be really nice if dscanner was able to tell me where to find all the module files that I am importing in a module and all the files that the imports import etc.

**Comment by wilzbach** [comment]
I am not sure whether this is dscanner's target as it's only a static code analysis tool. 
However afaik for example @joakim-noah  is using the dmd frontend to get an import lists which he uses to rewrite the imports in Phobos to selective ones.

**Comment by jcrapuchettes** [comment]
@Hackerpilot is actually standing next to me as I write this issue.

**Comment by wilzbach** [comment]
btw do you know [DBuildStat](https://github.com/CyberShadow/DBuildStat)?

See Martin's tutorial https://code.dawg.eu/reducing-vibed-turnaround-time-part-2-less-compiling.html

**Comment by Hackerpilot** [comment]
DBuildStat, ironically, doesn't build.
