### ISSUE TITLE
skipTests doesn't seem to work

### ISSUE THREAD

**Issue by JackStouffer** [Hackerpilot/Dscanner#358]
```
$ dscanner --version
v0.4.0-alpha 5c5a7572ea474a5969a6b6f6236ea82a64bad844
$ dscanner --styleCheck --skipTests std/math.d
```

prints a whole bunch of warnings about the code in the unit tests

**Comment by Hackerpilot** [comment]
I'm not able to reproduce this issue. Can you give an example of a line in a unittest block that's causing warnings?

**Comment by JackStouffer** [comment]
Forgot to update my `.bashrc`, I made some specific rules for commands in my D directory.

I apologize for the noise.
