### ISSUE TITLE
wrong comma expression warning

### ISSUE THREAD

**Issue by WebFreak001** [Hackerpilot/Dscanner#375]
```d
// test.d
void foo(int a, int b) {}

void bar() {
	int i;
	foo(i = 3, 5);
}
```

```
dscanner -S test.d
test.d(5:10)[warn]: Avoid using the comma expression.
```

**Comment by Hackerpilot** [comment]
You've discovered another ambiguity in the D grammar.

**Comment by Hackerpilot** [comment]
I'm not even sure how to fix this, because parsing it as `foo(` `i = 3, 5` `);` is valid.

**Comment by Hackerpilot** [comment]
Disregard the above. The grammar uses `AssignExpression` in argument lists and not `Expression`.
