### ISSUE TITLE
__FILE_FULL_PATH__ not recognized

### ISSUE THREAD

**Issue by timotheecour** [Hackerpilot/Dscanner#391]
`dscanner --declaration fun` fails with:
`auto fun(string file=__FILE_FULL_PATH__)(){}`

to avoid such errors in future, could there be test that checks against identifiers defined in https://dlang.org/spec/traits.html (for eg)

**Comment by BBasile** [comment]
It's probably because of this: https://github.com/Hackerpilot/libdparse/pull/120.
