### ISSUE TITLE
Skip unittests doesn't work for checking number literals

### ISSUE THREAD

**Issue by JackStouffer** [Hackerpilot/Dscanner#410]

**Comment by BBasile** [comment]
WHich check exactly ?

for this

```d
unittest
{
    ulong a = 100000000000;
}
```

The warning `Use underscores to improve number constant readability` is well skipped with `--skipTests`

**Comment by JackStouffer** [comment]
When enabling the check on the phobos config, tests in std.algorithm.iteration show up in the results of the scan.

```
$ make -f posix.mak style
...
std/algorithm/iteration.d(4820:42)[warn]: Use underscores to improve number constant readability.
std/algorithm/iteration.d(4823:51)[warn]: Use underscores to improve number constant readability.
std/algorithm/iteration.d(4825:50)[warn]: Use underscores to improve number constant readability.
```

All three of those lines are in a unit test

**Comment by JackStouffer** [comment]
Jesus I'm an idiot. I forgot to set it to `"skip-unittest"` and not to `"enabled"`.

This is like the fourth time I've made an issue on dscanner where the problem was really user error.
